spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver


  cache:
    type: redis
    redis:
      time-to-live: 7200 # 데이터 유지 시간(sec)
      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 6379


  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  properties:
    hibernate.format_sql: true
    hibernate.default_batch_fetch_size: 100


jwt:
  secret-key: fastcampus-mini-project-2
  # 2 hours
  expired-time-ms: 7200000